//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Satislars = new HashSet<Satislar>();
        }
    
        public int MusteriID { get; set; }
        [Required(ErrorMessage = "Bu alanı  Boş Bırakmayınız!")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik isim girin")]
        public string MusteriAd { get; set; }
        [Required(ErrorMessage = " Bu alanı   Boş Bırakmayınız!")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakterlik isim girin")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislars { get; set; }
    }
}
